### ISSUE TITLE
Expose an arg to set the path to Cake Core

### ISSUE THREAD

**Issue by CaptainQuirk** [julio6114/powerline_cakephp#1]
Hi there,

Sometimes, you need to change the CAKE_CORE_INCLUDE_PATH constant in your cakephp application, when your server prevents you to create a directory named **lib** at the root of your hosting space !
Could you expose a **cake_core_include_path** arg to be configured for your segment ?

Thanks for your work !

**Comment by ElRochito** [comment]
Hi!

It's done! See https://github.com/julio6114/powerline_cakephp/commit/76d4efcc7b87be905d3ad8174ef255267aea2b99

Enjoy!
